import type { Company } from './types';

/**
 * The single company data source for member and exporter surfaces.
 *
 * Every company below is drawn from the NZ Marine Export Group list on the
 * original site. Logos are the real, current marks harvested from each
 * company's own website (2026-07); `logoTheme: 'ink'` marks companies that
 * publish a reversed (white) logo, which renders on the navy card.
 *
 * URLs were health-checked 2026-07: Ultralon moved to ultralonfoam.com,
 * Tru Design to trudesign.nz, Babcock's old deep link 404s (now /marine/),
 * and Navigator Shipbrokers' navshipyachts.co.nz no longer resolves so the
 * working navship.co.nz is used. Regions are stated only where known.
 */
export const companies: Company[] = [
  {
    slug: '37-south',
    name: '37 South',
    url: 'https://www.37southyachts.com',
    category: 'Services',
    blurb: 'Superyacht agents supporting visiting yachts across New Zealand and the South Pacific.',
    logo: '/img/members/37-south.svg',
    logoTheme: 'ink',
    region: 'Auckland',
    recognised: true,
    exporter: true,
  },
  {
    slug: 'anura',
    name: 'Anura Amphibious Systems',
    url: 'https://www.anura.nz',
    category: 'Propulsion',
    blurb: 'Retractable amphibious systems supplied to boat manufacturers worldwide.',
    logo: '/img/members/anura.png',
    logoTheme: 'paper',
    recognised: true,
    exporter: true,
  },
  {
    slug: 'babcock',
    name: 'Babcock NZ',
    url: 'https://www.babcock.com.au/what-we-do/marine/',
    category: 'Services',
    blurb: "Marine engineering and superyacht services from Auckland's Devonport dockyard.",
    logo: '/img/members/babcock.png',
    logoTheme: 'paper',
    region: 'Auckland',
    recognised: true,
    exporter: true,
  },
  {
    slug: 'balex-marine',
    name: 'Balex Marine',
    url: 'https://www.balexmarine.com',
    category: 'Components',
    blurb: 'Automatic boat loaders that launch and retrieve trailer boats straight from the water.',
    logo: '/img/members/balex-marine.png',
    logoTheme: 'ink',
    region: 'Tauranga',
    recognised: true,
    exporter: true,
  },
  {
    slug: 'c-quip',
    name: 'C-Quip',
    url: 'https://www.c-quip.com',
    category: 'Components',
    blurb: 'Superyacht deck equipment designed and manufactured in New Zealand.',
    logo: '/img/members/c-quip.svg',
    logoTheme: 'ink',
    recognised: true,
    exporter: true,
  },
  {
    slug: 'c-tech',
    name: 'C-Tech',
    url: 'https://www.c-tech.co.nz',
    category: 'Sails & Rigging',
    blurb: 'Carbon fibre spars, battens and custom composites raced around the world.',
    logo: '/img/members/c-tech.png',
    logoTheme: 'ink',
    region: 'Auckland',
    recognised: true,
    exporter: true,
  },
  {
    slug: 'circa-marine',
    name: 'Circa Engineering & Marine',
    url: 'https://www.circamarine.co.nz',
    category: 'Boat Builders',
    blurb: 'Custom aluminium vessels designed, built and refitted in Whangārei.',
    logo: '/img/members/circa-marine.png',
    logoTheme: 'ink',
    region: 'Whangārei',
    recognised: true,
    exporter: true,
  },
  {
    slug: 'connex-wire',
    name: 'Connex Wire',
    url: 'https://www.connexwire.com',
    category: 'Electronics',
    blurb: 'Wiring harnesses and electrical systems engineered for marine manufacturers.',
    logo: '/img/members/connex-wire.svg',
    logoTheme: 'ink',
    recognised: true,
    exporter: true,
  },
  {
    slug: 'diverse-projects',
    name: 'Diverse Projects',
    url: 'https://www.diverseprojects.com',
    category: 'Services',
    blurb: 'New-build, refit and maintenance support across the superyacht lifecycle.',
    logo: '/img/members/diverse-projects.png',
    logoTheme: 'paper',
    recognised: true,
    exporter: true,
  },
  {
    slug: 'dixon',
    name: 'Marine Xpress / Dixon Manufacturing',
    url: 'https://www.dixon.co.nz',
    category: 'Components',
    blurb: 'Stainless steel fabrication and marine hardware made since 1976.',
    logo: '/img/members/dixon.png',
    logoTheme: 'paper',
    recognised: true,
    exporter: true,
  },
  {
    slug: 'doyle-sails',
    name: 'Doyle Sails',
    url: 'https://www.doylesails.com',
    category: 'Sails & Rigging',
    blurb: 'Performance sails made by sailors, with lofts worldwide and headquarters in Auckland.',
    logo: '/img/members/doyle-sails.png',
    logoTheme: 'paper',
    region: 'Auckland',
    recognised: true,
    exporter: true,
  },
  {
    slug: 'enl',
    name: 'Electronic Navigation Ltd',
    url: 'https://www.enl.co.nz',
    category: 'Electronics',
    blurb: 'Marine electronics for seabed survey, defence, fishing fleets and superyachts.',
    logo: '/img/members/enl.png',
    logoTheme: 'paper',
    region: 'Auckland',
    recognised: true,
    exporter: true,
  },
  {
    slug: 'fastmount',
    name: 'Fastmount',
    url: 'https://www.fastmount.com',
    category: 'Components',
    blurb: 'Panel mounting systems fitted in superyacht interiors worldwide.',
    logo: '/img/members/fastmount.png',
    logoTheme: 'paper',
    region: 'Auckland',
    recognised: true,
    exporter: true,
  },
  {
    slug: 'garmin',
    name: 'Garmin New Zealand',
    url: 'https://www.garmin.com/en-NZ/c/marine',
    category: 'Electronics',
    blurb: 'Chartplotters, sonar, radar and autopilots for every kind of boating.',
    logo: '/img/members/garmin.svg',
    logoTheme: 'paper',
    region: 'Auckland',
    recognised: true,
    exporter: true,
  },
  {
    slug: 'hamiltonjet',
    name: 'HamiltonJet',
    url: 'https://www.hamiltonjet.com',
    category: 'Propulsion',
    blurb: 'Waterjet propulsion designed in Christchurch and driving vessels worldwide.',
    logo: '/img/members/hamiltonjet.png',
    logoTheme: 'ink',
    region: 'Christchurch',
    recognised: true,
    exporter: true,
  },
  {
    slug: 'lloyd-stevenson',
    name: 'Lloyd Stevenson Boat Builders',
    url: 'https://www.lloydstevensonyachts.co.nz',
    category: 'Boat Builders',
    blurb: 'Custom composite launches, tenders and race boats built in Auckland.',
    logo: '/img/members/lloyd-stevenson.png',
    logoTheme: 'paper',
    region: 'Auckland',
    recognised: true,
    exporter: true,
  },
  {
    slug: 'marine-management',
    name: 'Marine Management',
    url: 'https://www.mml.org.nz',
    category: 'Services',
    blurb: 'Turn-key project management for marine builds and refits.',
    logo: '/img/members/marine-management.png',
    logoTheme: 'ink',
    region: 'Auckland',
    recognised: true,
    exporter: true,
  },
  {
    slug: 'martronics',
    name: 'Martronics',
    url: 'https://martronics.com',
    category: 'Electronics',
    blurb: 'Marine electrical systems and electronics, designed and built in Tauranga.',
    logo: '/img/members/martronics.png',
    logoTheme: 'paper',
    region: 'Tauranga',
    recognised: true,
    exporter: true,
  },
  {
    slug: 'maxtek',
    name: 'Maxtek Marine',
    url: 'https://www.maxtekmarine.com',
    category: 'Components',
    blurb: 'Marine steering systems engineered for workboats and pleasure craft.',
    logo: '/img/members/maxtek.png',
    logoTheme: 'paper',
    recognised: true,
    exporter: true,
  },
  {
    slug: 'mcmullen-wing',
    name: 'McMullen & Wing',
    url: 'https://www.mcmullenandwing.com',
    category: 'Boat Builders',
    blurb: 'Custom yachts and commercial vessels in steel, aluminium and composite.',
    logo: '/img/members/mcmullen-wing.png',
    logoTheme: 'ink',
    region: 'Auckland',
    recognised: true,
    exporter: true,
  },
  {
    slug: 'navico',
    name: 'Navico Group',
    url: 'https://www.navico.com',
    category: 'Electronics',
    blurb: 'Marine electronics spanning Simrad, B&G, Lowrance and C-MAP.',
    logo: '/img/members/navico.svg',
    logoTheme: 'ink',
    region: 'Auckland',
    recognised: true,
    exporter: true,
  },
  {
    slug: 'navigator-shipbrokers',
    name: 'Navigator Shipbrokers',
    url: 'http://www.navship.co.nz',
    category: 'Services',
    blurb: "Yacht transport to and from New Zealand as Sevenstar's local agents.",
    logo: '/img/members/navigator-shipbrokers.png',
    logoTheme: 'paper',
    region: 'Auckland',
    recognised: true,
    exporter: true,
  },
  {
    slug: 'north-sails',
    name: 'North Sails',
    url: 'https://www.northsails.com',
    category: 'Sails & Rigging',
    blurb: "The world's largest sailmaker, serving racing and cruising sailors.",
    logo: '/img/members/north-sails.svg',
    logoTheme: 'paper',
    region: 'Auckland',
    recognised: true,
    exporter: true,
  },
  {
    slug: 'orams-marine',
    name: 'Orams Marine',
    url: 'https://www.oramsmarine.co.nz',
    category: 'Services',
    blurb: "The South Pacific's leading superyacht refit and maintenance yard.",
    logo: '/img/members/orams-marine.svg',
    logoTheme: 'paper',
    region: 'Auckland',
    recognised: true,
    exporter: true,
  },
  {
    slug: 'pacific-aerials',
    name: 'Pacific Aerials',
    url: 'https://www.pacificaerials.co.nz',
    category: 'Electronics',
    blurb: 'Marine antennas engineered for reliable communication at sea.',
    logo: '/img/members/pacific-aerials.svg',
    logoTheme: 'ink',
    region: 'Auckland',
    recognised: true,
    exporter: true,
  },
  {
    slug: 'propspeed',
    name: 'Propspeed',
    url: 'https://www.propspeed.com',
    category: 'Components',
    blurb: 'The original foul-release coating for propellers and running gear.',
    logo: '/img/members/propspeed.png',
    logoTheme: 'paper',
    region: 'Auckland',
    recognised: true,
    exporter: true,
  },
  {
    slug: 'q-west',
    name: 'Q-West Boat Builders',
    url: 'https://www.q-west.com',
    category: 'Boat Builders',
    blurb: 'Aluminium ferries, workboats and charter vessels built in Whanganui.',
    logo: '/img/members/q-west.png',
    logoTheme: 'ink',
    region: 'Whanganui',
    recognised: true,
    exporter: true,
  },
  {
    slug: 'sce-stone',
    name: 'SCE Stone & Design',
    url: 'https://www.scestoneanddesign.co.nz',
    category: 'Components',
    blurb: 'Lightweight stone surfaces crafted for superyacht and residential interiors.',
    logo: '/img/members/sce-stone.png',
    logoTheme: 'paper',
    recognised: true,
    exporter: true,
  },
  {
    slug: 'sealegs',
    name: 'Sealegs',
    url: 'https://www.sealegs.com',
    category: 'Boat Builders',
    blurb: 'Amphibious boats trusted for rescue, patrol, tourism and waterfront boating.',
    logo: '/img/members/sealegs.png',
    logoTheme: 'ink',
    region: 'Auckland',
    recognised: true,
    exporter: true,
  },
  {
    slug: 'smuggler-marine',
    name: 'Smuggler Marine',
    url: 'https://www.smuggler.co.nz',
    category: 'Boat Builders',
    blurb: 'High-performance RIBs and amphibious boats built in Auckland.',
    logo: '/img/members/smuggler-marine.svg',
    logoTheme: 'ink',
    region: 'Auckland',
    recognised: true,
    exporter: true,
  },
  {
    slug: 'southern-spars',
    name: 'Southern Spars',
    url: 'https://www.southernspars.com',
    category: 'Sails & Rigging',
    blurb: 'Composite masts and rigging for grand prix yachts and superyachts.',
    logo: '/img/members/southern-spars.png',
    logoTheme: 'paper',
    region: 'Auckland',
    recognised: true,
    exporter: true,
  },
  {
    slug: 'tectrax',
    name: 'Tectrax',
    url: 'https://www.tectrax.co.nz',
    category: 'Propulsion',
    blurb: 'Fully electric amphibious drive systems for next-generation boating.',
    logo: '/img/members/tectrax.png',
    logoTheme: 'ink',
    recognised: true,
    exporter: true,
  },
  {
    slug: 'tnl-pindar',
    name: 'TNL Pindar',
    url: 'https://www.tnlpindar.com',
    category: 'Services',
    blurb: 'Specialist logistics moving boats, masts and race equipment worldwide.',
    logo: '/img/members/tnl-pindar.png',
    logoTheme: 'paper',
    recognised: true,
    exporter: true,
  },
  {
    slug: 'tru-design',
    name: 'Tru Design Plastics',
    url: 'https://www.trudesign.nz',
    category: 'Components',
    blurb: 'Composite seacocks, skin fittings and plumbing certified for hulls worldwide.',
    logo: '/img/members/tru-design.png',
    logoTheme: 'ink',
    recognised: true,
    exporter: true,
  },
  {
    slug: 'ultralon',
    name: 'Ultralon Foam Group',
    url: 'https://www.ultralonfoam.com',
    category: 'Components',
    blurb: 'EVA foam decking and engineered foam products for the marine industry.',
    logo: '/img/members/ultralon.png',
    logoTheme: 'ink',
    recognised: true,
    exporter: true,
  },
  {
    slug: 'vmg-clothing',
    name: 'VMG Clothing',
    url: 'https://www.vmgclothing.com',
    category: 'Apparel',
    blurb: 'Crew uniforms and marine apparel for superyachts and race teams.',
    logo: '/img/members/vmg-clothing.png',
    logoTheme: 'paper',
    recognised: true,
    exporter: true,
  },
];
